# Generated by Django 2.1.7 on 2019-03-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='answers_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions_site.Answers'),
        ),
    ]
