version: '3.7'

services:
  rabbit:
    image: rabbitmq:latest
    restart: always
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: 'kailiak'
      RABBITMQ_DEFAULT_PASS: 'password'
    volumes:
      - rabbit_data:/var/lib/rabbitmq/mnesia
  
  consumer:
    build: consumer
    environment:
      RABBIT_URL: 'amqp://kailiak:password@rabbit:5672'
      DB_URL: 'dbname=ints_db user=postgres password=password host=postgres'
    depends_on: 
      - rabbit
  producer:
    build: producer
    environment:
      RABBIT_URL: 'amqp://kailiak:password@rabbit:5672'
    depends_on:
      - rabbit
    

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'ints_db'

    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  rabbit_data:
  postgres_data:
